"""Build source_map.md: web section -> heading in the PDF -> source lines shown.

Usage: python3 tools/make_source_map.py   (run from eu-presentation/)
Reads index.html; writes source_map.md.
"""
from html.parser import HTMLParser
import pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent


class Sections(HTMLParser):
    def __init__(self):
        super().__init__()
        self.rows, self.cur, self.stack, self.capture = [], None, [], None

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        cls = a.get("class", "") or ""
        if tag == "section" and "id" in a:
            self.cur = {"id": a["id"], "pdf": a.get("data-pdf", ""), "label": "", "title": "", "src": [], "caps": []}
            self.rows.append(self.cur)
        if self.cur is None:
            return
        key = None
        if "eyebrow" in cls.split():
            key = "label"
        elif tag in ("h1", "h2") and not self.cur["title"]:
            key = "title"
        elif "src" in cls.split():
            key = "src"
        elif tag in ("caption", "figcaption") or "cap" in cls.split():
            key = "caps"
        if key:
            self.capture = [key, tag, []]
        if self.capture:
            self.stack.append(tag)

    def handle_endtag(self, tag):
        if self.capture and self.stack:
            self.stack.pop()
            if not self.stack:
                key, _, buf = self.capture
                text = re.sub(r"\s+", " ", "".join(buf)).strip()
                if key in ("src", "caps"):
                    self.cur[key].append(text)
                elif not self.cur[key]:
                    self.cur[key] = text
                self.capture = None

    def handle_data(self, data):
        if self.capture:
            self.capture[2].append(data)


p = Sections()
p.feed((ROOT / "index.html").read_text(encoding="utf-8"))
out = ["# Source map", "",
       "Generated by `tools/make_source_map.py` from `index.html`. "
       "Source of truth: *BTL Đa biên - Nhóm 4.pdf*.", "",
       "| # | Web section (id) | Label · title on the page | Heading in the PDF | Tables / figures | Source line shown |",
       "|---|---|---|---|---|---|"]
for i, r in enumerate(p.rows, 1):
    src = "<br>".join(r["src"]) or "(none shown)"
    caps = "<br>".join(r["caps"]) or ""
    out.append(f"| {i} | `#{r['id']}` | {r['label']} · {r['title']} | {r['pdf']} | {caps} | {src} |")
(ROOT / "source_map.md").write_text("\n".join(out) + "\n", encoding="utf-8")
print(f"source_map.md: {len(p.rows)} sections")
